In [114]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense , Flatten , Conv2D , MaxPooling2D

## Tensorflow for experts
its begginer version , often used for simple or small networks and tasks .<br>
like  simple classification , regression ...<br>

but for huge models like chatgpt , and real world problems , we need to do all tasks ourselves , like compiling , training , evaluating .
all of these steps we have used were automatic : <br>
model.compile() <br>
model.fit() <br>
model.evaluate() <br>
<br>
but now we are going to do all of these ourselves

### Train MNIST Dataset , with this more difficult way :

# steps :
0_ load data <br>
1_ normalize data (pixels) <br>
2_ check numbers of channels (in case of gray scale image , unsqueeze X data.
<br>
4_ Adding batch size , shuffle , and etc.


In [115]:
MNIST = keras.datasets.mnist

# تابع لود دیتا ۴ تا مقدار برمیگردونه یعنی دو تا تاپل
#Returns:
#  Tuple of NumPy arrays: (x_train, y_train), (x_test, y_test).
(x_train , y_train) , (x_test , y_test) = MNIST.load_data()

x_train[900]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         22, 137, 243, 255, 173,   2,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  20,
        185, 202,  87,  90, 254,   6,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  31, 214,
        160,   8,   0,  70, 254,   6,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 202, 185,
          3,   0,   0,  77, 232,   4,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  97, 250,  22,
          0,   0,   1, 177, 138,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  23, 227, 146,   0,
          0,   0,  15, 254,  76,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  73, 254,  53,   0,
          0,   6, 191, 254,  63,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  73, 254,  17,   0,
         61, 200, 254, 252,  34,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  44, 244, 196, 158,
        244, 164, 225, 206,  17,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  51, 185, 221,
        152,  18, 211, 184,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  21, 237, 104,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 128, 246,  23,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 155, 240,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 155, 174,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 168, 161,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         14, 235,  99,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         59, 254,  43,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        100, 246,  29,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

In [116]:
# normalizing pixels :
x_train , x_test = x_train/255.0 , x_test/255.0 # should be float

In [117]:
x_train[5].shape

(28, 28)

because we want to use 2D conv , so we have to convert (28,28) image , into a 3 channel image : <br>
(28,28,1)
<br>
* ps : in other datasets we dont have this problem . for example , in CIFAR10 , images have 3 channels their selves (32,32,3) .


In [118]:
# or
#x_train = x_train.reshape()

#or
#x_train = tf.expand_dims(x_train , axis=3)
#x_train[5].shape

In [119]:
# add channel layer - << unsqueeze >>
x_train = x_train[... , tf.newaxis]
x_test = x_test[... , tf.newaxis]
x_train[5].shape

(28, 28, 1)

In [120]:
type(x_train[5][0,0,0])

numpy.float64

## Adding batch size :

In [121]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train , y_train)).batch(32).shuffle(buffer_size=1000)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test , y_test)).batch(32)

# we only need to shuffle train data

## creating model using object oriented

In [122]:
class MyModel(tf.keras.Model):
  def __init__(self):
    super().__init__()

    # define network layers
    self.conv2D_1  = Conv2D(32 ,3 , activation="relu") # 32 filter with size = 3
    self.conv2D_2  = Conv2D(64 ,3 , activation="relu")
    self.maxpool2D = MaxPooling2D()
    self.flatten = Flatten()
    self.dense1 = Dense(128 , activation="relu")
    self.dense2 = Dense(10)


  def call(self , x):
    x = self.conv2D_1(x)
    x = self.maxpool2D(x)
    x = self.conv2D_2(x)
    x = self.maxpool2D(x)
    x = self.flatten(x)
    x = self.dense1(x)
    x = self.dense2(x)
    return x



model = MyModel()

## implement compile and fit methods :

In [123]:
# REAL / MAIN loss-function uses in train stage -
# which affect on updating network's weights
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam()


In [124]:
# these are METRICS
# they are not going to use in train process

# another loss which we use in evaluation
train_loss = tf.keras.metrics.Mean()
test_loss = tf.keras.metrics.Mean()

# bc problem is classification , so we also need accuracy
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

# TRAIN

## important tip ::
## we should RESET VALUES of : <br>
### train loss , train acc , test loss , test acc , IN EACH EPOCH

چون داخل خود مدل وزن ها داره آپدیت میشه و مدل یک متغییر گلوبال هست نیازی نیست در توابع ترین و تست چیزی ریترن بشه

@tf.function : <br>
please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing.

In [125]:
@tf.function
def train(images , labels):
    with tf.GradientTape() as tape : # compute gradient
      # 1_ give data to network :
      prediction = model(images)
      # 2_ compare these preddictions with real labels & compute loss :
      loss = loss_function(labels , prediction)
    # 3_ compute GRADIENTS
    gradients = tape.gradient(loss , model.trainable_variables) # trainable netwok weights

    # 4_update weights :
    optimizer.apply_gradients(grads_and_vars= zip(gradients , model.trainable_variables))

    train_loss(loss)
    train_accuracy(labels , prediction)


In [126]:
@tf.function
def test(images , labels):
  # it looks like train stage , but without computing gradients
  # ps : in test phase we dont need to compute moshtagh(gradients)
  prediction = model(images)
  loss = loss_function(y_true=labels , y_pred=prediction)
  test_loss(loss)
  test_accuracy(labels , prediction)



In [127]:
epochs = 8
for epoch in range(epochs):
  train_loss.reset_states()
  train_accuracy.reset_states()
  test_loss.reset_states()
  test_accuracy.reset_states()

  #train
  for images , labels in train_dataset :
    train(images , labels)

  # test
  for images , labels in test_dataset :
    test(images , labels)


  print("epoch:" , epoch + 1  ,
        f"Train Loss: {train_loss.result()}" ,
        f"Train Acc: {train_accuracy.result()}" ,
        f"Test loss: {test_loss.result()}",
        f"Test Acc: {test_accuracy.result()}")

epoch: 1 Train Loss: 0.1338050365447998 Train Acc: 0.9590333104133606 Test loss: 0.0361843965947628 Test Acc: 0.9876999855041504
epoch: 2 Train Loss: 0.04314655065536499 Train Acc: 0.9863666892051697 Test loss: 0.036130405962467194 Test Acc: 0.9886000156402588
epoch: 3 Train Loss: 0.0305416751652956 Train Acc: 0.9898333549499512 Test loss: 0.03035852499306202 Test Acc: 0.9896000027656555
epoch: 4 Train Loss: 0.020896289497613907 Train Acc: 0.9935500025749207 Test loss: 0.02825453318655491 Test Acc: 0.9908000230789185
epoch: 5 Train Loss: 0.016112733632326126 Train Acc: 0.9947166442871094 Test loss: 0.03157404065132141 Test Acc: 0.9902999997138977
epoch: 6 Train Loss: 0.0115890521556139 Train Acc: 0.9960166811943054 Test loss: 0.036296993494033813 Test Acc: 0.9907000064849854
epoch: 7 Train Loss: 0.010043875314295292 Train Acc: 0.9966999888420105 Test loss: 0.03119869902729988 Test Acc: 0.9894000291824341
epoch: 8 Train Loss: 0.007445247378200293 Train Acc: 0.9975000023841858 Test loss:

In [128]:
model.save("advanced_tf_model_mnist")

# INFERENCE stage :
TEST an iamge

In [129]:
model = tf.keras.models.load_model("advanced_tf_model_mnist")

In [130]:
import cv2
import numpy as np

image =  cv2.imread("seven.png")
image = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)
image = cv2.resize(image , (28,28))
image = image[...,tf.newaxis]
image = image.astype("float32") # bc new image is integer so it should be converted to float
image.shape


(28, 28, 1)

In [131]:
# data should enter the network in batch shape
# for example :
# if  batch size = 32
# then : we have (32 , 28 , 28 , 1)

# but now be have only 1 image for test , so :
# (1 , 28 , 28 , 1 )

image  = image[tf.newaxis , ...]
image.shape
#(batchsize , width , height , img_channel_number)
# if we had colored image , img_channel_number became 3

(1, 28, 28, 1)

# so network likes to get a 4D input
(batchsize , width , height , img_channel_number)

In [132]:
prediction = model(image)
prediction

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-3872.9617 , -2256.079  ,  -335.79745,   839.97314,    26.22779,
        -1813.1091 , -5181.0127 ,  6131.1865 , -1705.3674 , -1412.0598 ]],
      dtype=float32)>

In [133]:
np.argmax(prediction)

7

## only this loss : loss='sparse_categorical_crossentropy'
is attending in train process . <br>
another losses like mae and mse dont attend in training process and dont affects network weights.

In [134]:
# for beginners version
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy', # use this loss for train , and updating weights
              metrics=['accuracy' , "mae" , "mse"])


model.fit(x_train, y_train,validation_split=0.2, epochs=8)
model.evaluate(x_test, y_test)

Epoch 1/8
1500/1500 [==============================] - 8s 4ms/step - loss: 0.3284 - accuracy: 0.9048 - val_loss: 0.1662 - val_accuracy: 0.9522
Epoch 2/8
1500/1500 [==============================] - 6s 4ms/step - loss: 0.1566 - accuracy: 0.9540 - val_loss: 0.1178 - val_accuracy: 0.9654
Epoch 3/8
1500/1500 [==============================] - 5s 3ms/step - loss: 0.1169 - accuracy: 0.9647 - val_loss: 0.0993 - val_accuracy: 0.9711
Epoch 4/8
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0991 - accuracy: 0.9702 - val_loss: 0.1000 - val_accuracy: 0.9696
Epoch 5/8
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0810 - accuracy: 0.9743 - val_loss: 0.0938 - val_accuracy: 0.9716
Epoch 6/8
1500/1500 [==============================] - 5s 3ms/step - loss: 0.0701 - accuracy: 0.9777 - val_loss: 0.0880 - val_accuracy: 0.9742
Epoch 7/8
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0617 - accuracy: 0.9802 - val_loss: 0.0837 - val_accuracy: 0.9748

[0.06786849349737167, 0.9793999791145325]